# Generated by Django 4.2.6 on 2023-10-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'оплата', 'verbose_name_plural': 'оплаты'},
        ),
    ]
